---

- hosts: all
  become: true
  tasks:

    - name: remove apache and php packages for ubuntu
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: remove apache and php packages for arch linux
      package:
        name:
          - apache
          - php-apache
        state: absent
      when: ansible_distribution == "Archlinux"
