---

- hosts: all
  become: true
  tasks:

    - name: remove packages for ubuntu
      package:
        name:
          - apache2
          - libapache2-mod-php
          - mariadb-server
          - samba
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: remove packages for arch linux
      package:
        name:
          - apache
          - php-apache
          - mariadb
          - samba
        state: absent
      when: ansible_distribution == "Archlinux"
