---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates ubuntu
      tags: always
      apt:
        upgrade: safe
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: install updates arch linux
      tags: always
      pacman:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == "Archlinux"

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php packages for ubuntu servers
      tags: web,apache,apache2,ubuntu
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
    
    - name: install apache and php packages for arch linux servers
      tags: web,apache,archlinux
      package:
        name:
          - apache
          - php-apache
        state: latest
      when: ansible_distribution == "Archlinux"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb for ubuntu servers
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb for arch linux servers
    tags: db,mariadb,archlinux
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "Archlinux"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package for ubuntu servers
      tags: file,samba,ubuntu
      apt:
        name: samba
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install samba package for arch linux servers
      tags: file,samba,archlinux
      package:
        name: samba
        state: latest
      when: ansible_distribution == "Archlinux"
