- name: install apache and php packages for ubuntu servers
  tags: web,apache,apache2,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php packages for arch linux servers
  tags: web,apache,archlinux
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Archlinux"

- name: start and enable apache2 for ubuntu
  tags: apache2,ubuntu
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: start and enable apache for arch linux
  tags: apache,archlinux
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_distribution == "Archlinux"

- name: change email address for admin for ubuntu
  tags: apache2,ubuntu
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin emrwo@emrwo.com
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache

#- name: restart apache2 for ubuntu
#  tags: apache2,ubuntu
#  service:
#    name: "{{ apache_service }}"
#    state: restarted
#  when: apache2.changed

- name: copy html file for site for ubuntu
  tags: apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu"

- name: copy html file for site for arch linux
  tags: apache
  copy:
    src: default_site.html
    dest: /srv/http/index.html
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Archlinux"
